export const IMAGES = {
  logo: new URL('~/assets/img/logo/logo.png', import.meta.url).href,
  app: {
    android: new URL('~/assets/img/apps/android.png', import.meta.url).href,
    apple: new URL('~/assets/img/apps/android.png', import.meta.url).href,
  },
  user:{
    defaultAvatar:'https://static.vecteezy.com/system/resources/previews/009/734/564/original/default-avatar-profile-icon-of-social-media-user-vector.jpg',
  },
  instagram: {
    image1: new URL('~/assets/img/insta/1.jpg', import.meta.url).href,
    image2: new URL('~/assets/img/insta/2.jpg', import.meta.url).href,
    image3: new URL('~/assets/img/insta/3.jpg', import.meta.url).href,
    image4: new URL('~/assets/img/insta/4.jpg', import.meta.url).href,
    image5: new URL('~/assets/img/insta/5.jpg', import.meta.url).href,
    image6: new URL('~/assets/img/insta/6.jpg', import.meta.url).href,
    image7: new URL('~/assets/img/insta/7.jpg', import.meta.url).href,
    image8: new URL('~/assets/img/insta/8.jpg', import.meta.url).href,
    image9: new URL('~/assets/img/insta/9.jpg', import.meta.url).href,
    image10: new URL('~/assets/img/insta/10.jpg', import.meta.url).href,
    image11: new URL('~/assets/img/insta/11.jpg', import.meta.url).href,
    image12: new URL('~/assets/img/insta/12.jpg', import.meta.url).href,
    image13: new URL('~/assets/img/insta/13.jpg', import.meta.url).href,
    image14: new URL('~/assets/img/insta/14.jpg', import.meta.url).href,
    image15: new URL('~/assets/img/insta/15.jpg', import.meta.url).href,
    image16: new URL('~/assets/img/insta/16.jpg', import.meta.url).href,
  },
  product: {
    image1: new URL('~/assets/img/product/1.jpg', import.meta.url).href,
    image2: new URL('~/assets/img/product/2.jpg', import.meta.url).href,
    image3: new URL('~/assets/img/product/3.jpg', import.meta.url).href,
    image4: new URL('~/assets/img/product/4.jpg', import.meta.url).href,
    image5: new URL('~/assets/img/product/5.jpg', import.meta.url).href,
    image6: new URL('~/assets/img/product/6.jpg', import.meta.url).href,
    image7: new URL('~/assets/img/product/7.jpg', import.meta.url).href,
    image8: new URL('~/assets/img/product/8.jpg', import.meta.url).href,
    image9: new URL('~/assets/img/product/9.jpg', import.meta.url).href,
    image10: new URL('~/assets/img/product/10.jpg', import.meta.url).href,
    image11: new URL('~/assets/img/product/11.jpg', import.meta.url).href,
    image12: new URL('~/assets/img/product/12.jpg', import.meta.url).href,
    image13: new URL('~/assets/img/product/13.jpg', import.meta.url).href,
    image14: new URL('~/assets/img/product/14.jpg', import.meta.url).href,
    i5mage15: new URL('~/assets/img/product/15.jpg', import.meta.url).href,
    image16: new URL('~/assets/img/product/16.jpg', import.meta.url).href,
    image17: new URL('~/assets/img/product/17.jpg', import.meta.url).href,
    image18: new URL('~/assets/img/product/18.jpg', import.meta.url).href,
    image19: new URL('~/assets/img/product/19.jpg', import.meta.url).href,
    image20: new URL('~/assets/img/product/20.jpg', import.meta.url).href,
    image21: new URL('~/assets/img/product/21.jpg', import.meta.url).href,
    image22: new URL('~/assets/img/product/22.jpg', import.meta.url).href,
    image23: new URL('~/assets/img/product/23.jpg', import.meta.url).href,
    image24: new URL('~/assets/img/product/24.jpg', import.meta.url).href,
    image25: new URL('~/assets/img/product/25.jpg', import.meta.url).href,
    image26: new URL('~/assets/img/product/26.jpg', import.meta.url).href,
    image27: new URL('~/assets/img/product/27.jpg', import.meta.url).href,
    image28: new URL('~/assets/img/product/28.jpg', import.meta.url).href,
    image29: new URL('~/assets/img/product/29.jpg', import.meta.url).href,
    image30: new URL('~/assets/img/product/30.jpg', import.meta.url).href,
    image31: new URL('~/assets/img/product/31.jpg', import.meta.url).href,
    image32: new URL('~/assets/img/product/32.jpg', import.meta.url).href,
    image33: new URL('~/assets/img/product/33.jpg', import.meta.url).href,
    image34: new URL('~/assets/img/product/34.jpg', import.meta.url).href,
    image35: new URL('~/assets/img/product/35.jpg', import.meta.url).href,
    image36: new URL('~/assets/img/product/36.jpg', import.meta.url).href,
    image37: new URL('~/assets/img/product/37.jpg', import.meta.url).href,
    image38: new URL('~/assets/img/product/38.jpg', import.meta.url).href,
    image39: new URL('~/assets/img/product/39.jpg', import.meta.url).href,
    image40: new URL('~/assets/img/product/40.jpg', import.meta.url).href,
    image41: new URL('~/assets/img/product/41.jpg', import.meta.url).href,
    image42: new URL('~/assets/img/product/42.jpg', import.meta.url).href,
    image43: new URL('~/assets/img/product/43.jpg', import.meta.url).href,
    image44: new URL('~/assets/img/product/44.jpg', import.meta.url).href,
    image45: new URL('~/assets/img/product/45.jpg', import.meta.url).href,
    image46: new URL('~/assets/img/product/46.jpg', import.meta.url).href,
    image47: new URL('~/assets/img/product/47.jpg', import.meta.url).href,
    image48: new URL('~/assets/img/product/48.jpg', import.meta.url).href,
    image49: new URL('~/assets/img/product/49.jpg', import.meta.url).href,
    image50: new URL('~/assets/img/product/50.jpg', import.meta.url).href,
    image51: new URL('~/assets/img/product/51.jpg', import.meta.url).href,
    image52: new URL('~/assets/img/product/52.jpg', import.meta.url).href,
    image53: new URL('~/assets/img/product/53.jpg', import.meta.url).href,
    image54: new URL('~/assets/img/product/54.jpg', import.meta.url).href,
    image55: new URL('~/assets/img/product/55.jpg', import.meta.url).href,
    image56: new URL('~/assets/img/product/56.jpg', import.meta.url).href,
    image57: new URL('~/assets/img/product/57.jpg', import.meta.url).href,
    image58: new URL('~/assets/img/product/58.jpg', import.meta.url).href,
    image59: new URL('~/assets/img/product/59.jpg', import.meta.url).href,
    image60: new URL('~/assets/img/product/60.jpg', import.meta.url).href,
  },
  productBanner: {
    image1: new URL('~/assets/img/product-banner/1.jpg', import.meta.url).href,
    image2: new URL('~/assets/img/product-banner/2.jpg', import.meta.url).href,
    image3: new URL('~/assets/img/product-banner/3.jpg', import.meta.url).href,
    image4: new URL('~/assets/img/product-banner/4.jpg', import.meta.url).href,
    image5: new URL('~/assets/img/product-banner/5.jpg', import.meta.url).href,
    image6: new URL('~/assets/img/product-banner/6.jpg', import.meta.url).href,
  },
  blog: {
    image1: new URL('~/assets/img/blog/1.jpg', import.meta.url).href,
    image2: new URL('~/assets/img/blog/2.jpg', import.meta.url).href,
    image3: new URL('~/assets/img/blog/3.jpg', import.meta.url).href,
    image4: new URL('~/assets/img/blog/4.jpg', import.meta.url).href,
    image5: new URL('~/assets/img/blog/5.jpg', import.meta.url).href,
    image6: new URL('~/assets/img/blog/6.jpg', import.meta.url).href,
    image7: new URL('~/assets/img/blog/7.jpg', import.meta.url).href,
    image8: new URL('~/assets/img/blog/8.jpg', import.meta.url).href,
    image9: new URL('~/assets/img/blog/9.jpg', import.meta.url).href,
  },
  review: {
    image1: new URL('~/assets/img/review/1.jpg', import.meta.url).href
  },
};
